import type { Notice, BookReview, Classic100, Program } from './types'

export const notices: Notice[] = [
  {
    id: 1,
    title: '2026년 1학기 독서프로그램 신청 안내',
    content: '2026년 1학기 독서프로그램 신청이 시작되었습니다. 이번 학기에는 독서 마라톤, 북 멘토링, 독서 에세이 대회 등 다양한 프로그램이 준비되어 있으니, 많은 관심과 참여 부탁드립니다.\n\n신청 기간은 2026년 2월 17일(월)부터 3월 7일(금)까지이며, 오거서 앱 또는 웹사이트를 통해 신청하실 수 있습니다. 프로그램별 정원이 제한되어 있으므로 조기 마감될 수 있습니다.\n\n문의사항은 학술정보관 독서교육팀(031-290-XXXX)으로 연락해 주시기 바랍니다.',
    date: '2026-02-03',
    views: 487,
    author: '독서교육팀',
    attachments: ['2026-1학기_독서프로그램_안내문.pdf', '프로그램_일정표.xlsx'],
    important: true,
  },
  {
    id: 2,
    title: '제15회 독서에세이 공모전 안내',
    content: '성균관대학교 학술정보관에서 제15회 독서에세이 공모전을 개최합니다. 이번 공모전은 "읽고, 생각하고, 나누다"를 주제로 진행되며, 재학생 누구나 참여 가능합니다.\n\n응모 기간은 2026년 3월 2일(월)부터 4월 30일(수)까지이며, 입상작에는 상장 및 상금이 수여됩니다. 대상(1명) 50만원, 최우수상(2명) 30만원, 우수상(5명) 10만원, 장려상(10명) 5만원입니다.\n\n자세한 응모 요강은 첨부파일을 참고하시기 바랍니다.',
    date: '2026-01-27',
    views: 312,
    author: '독서교육팀',
    attachments: ['제15회_독서에세이_공모전_요강.pdf'],
    important: false,
  },
  {
    id: 3,
    title: '성균 고전 100선 2026년 개정판 안내',
    content: '성균 고전 100선이 2026년 개정판으로 새롭게 업데이트되었습니다. 이번 개정에서는 자연과학 분야 도서 5종이 교체되었으며, 각 도서의 해제가 전면 개정되었습니다.\n\n개정된 목록은 오거서 앱 및 학술정보관 홈페이지에서 확인하실 수 있으며, 인쇄본 책자는 학술정보관 1층 안내데스크에서 배부하고 있습니다.\n\n성균 고전 100선은 본교 교양교육의 핵심으로, 재학 기간 동안 다양한 고전을 접하고 깊이 있는 사유를 경험할 수 있도록 마련된 프로그램입니다.',
    date: '2026-01-20',
    views: 398,
    author: '학술정보관',
    attachments: ['성균고전100선_2026_개정목록.pdf'],
    important: true,
  },
  {
    id: 4,
    title: '오거서 앱 업데이트 안내 (v3.2)',
    content: '오거서 앱이 v3.2로 업데이트되었습니다. 이번 업데이트에서는 독서 기록 통계 기능이 강화되었으며, 독서 모임 채팅 기능이 새롭게 추가되었습니다.\n\n주요 변경사항: 독서 달력 뷰 개선, 리뷰 작성 시 사진 첨부 기능 추가, 푸시 알림 설정 세분화, 다크 모드 지원이 포함됩니다.\n\n앱스토어 및 구글 플레이스토어에서 최신 버전으로 업데이트해 주시기 바랍니다.',
    date: '2026-01-15',
    views: 256,
    author: '정보시스템팀',
    attachments: [],
    important: false,
  },
  {
    id: 5,
    title: '2025학년도 2학기 우수 독서인 시상',
    content: '2025학년도 2학기 우수 독서인으로 선정된 학우들을 축하합니다. 이번 학기에는 총 20명의 학우가 우수 독서인으로 선정되었습니다.\n\n선정 기준은 독서 활동 참여도, 서평 작성 품질, 독서 토론 기여도 등을 종합적으로 평가하였습니다. 수상자에게는 상장과 도서 상품권이 수여됩니다.\n\n시상식은 2026년 1월 10일(금) 오후 3시 학술정보관 세미나실에서 진행되었습니다.',
    date: '2025-12-30',
    views: 189,
    author: '독서교육팀',
    attachments: ['2025-2학기_우수독서인_명단.pdf'],
    important: false,
  },
  {
    id: 6,
    title: '겨울방학 독서캠프 참가자 모집',
    content: '2026년 겨울방학 독서캠프 참가자를 모집합니다. 이번 캠프는 "고전과 함께하는 3일"이라는 주제로, 성균 고전 100선 중 엄선된 도서를 집중적으로 읽고 토론하는 프로그램입니다.\n\n일시는 2026년 1월 20일(월)부터 1월 22일(수)까지 2박 3일이며, 장소는 자연과학캠퍼스 수련관입니다. 참가비는 무료이며 숙식이 제공됩니다.\n\n모집 인원은 40명이며, 선착순으로 마감합니다. 신청은 오거서 앱에서 가능합니다.',
    date: '2025-12-20',
    views: 345,
    author: '독서교육팀',
    attachments: ['겨울독서캠프_안내문.pdf', '캠프_일정표.pdf'],
    important: false,
  },
  {
    id: 7,
    title: '도서관 북토크 일정 안내',
    content: '2026년 상반기 도서관 북토크 일정을 안내드립니다. 매월 마지막 주 수요일 오후 4시에 학술정보관 다목적홀에서 진행되며, 각 분야 전문가와 함께 깊이 있는 독서 대화를 나눌 수 있습니다.\n\n2월 북토크는 소설가 김영하 작가를 초청하여 "문학과 기억"을 주제로 진행합니다. 3월에는 철학자 김상환 교수(서울대)가 "동양 고전의 현대적 읽기"를 주제로 강연합니다.\n\n참여를 원하시는 분은 오거서 앱에서 사전 신청해 주시기 바랍니다. 현장 참여도 가능하나 좌석이 제한될 수 있습니다.',
    date: '2025-12-15',
    views: 213,
    author: '학술정보관',
    attachments: ['2026_상반기_북토크_일정.pdf'],
    important: false,
  },
  {
    id: 8,
    title: '독서토론 리더 모집 공고',
    content: '2026년 1학기 독서토론 리더를 모집합니다. 독서토론 리더는 소규모 독서 모임을 이끌며, 참여 학우들의 독서 활동을 촉진하는 역할을 합니다.\n\n지원 자격은 2학기 이상 재학생으로, 독서프로그램 참여 경험이 1회 이상인 학우입니다. 선발된 리더에게는 활동 장학금(학기당 30만원)과 리더십 인증서가 수여됩니다.\n\n지원 기간은 2026년 2월 3일(월)부터 2월 21일(금)까지이며, 오거서 앱 또는 학술정보관 홈페이지에서 지원서를 제출하시면 됩니다.',
    date: '2025-12-10',
    views: 178,
    author: '독서교육팀',
    attachments: ['독서토론리더_모집요강.pdf', '지원서_양식.hwp'],
    important: false,
  },
  {
    id: 9,
    title: '2026년 신간 도서 추천 리스트',
    content: '학술정보관에서 2026년 주목할 만한 신간 도서 추천 리스트를 발표합니다. 각 분야 교수님들의 추천과 학생 투표를 통해 선정된 50권의 도서를 소개합니다.\n\n추천 도서는 문학, 인문, 사회과학, 자연과학, 예술 등 다양한 분야를 아우르며, 학술정보관 1층 "이달의 추천 도서" 코너에서 만나보실 수 있습니다.\n\n전체 추천 리스트는 첨부파일과 오거서 앱에서 확인 가능하며, 대출 예약도 앱을 통해 하실 수 있습니다.',
    date: '2025-12-05',
    views: 267,
    author: '학술정보관',
    attachments: ['2026_신간추천_리스트.pdf'],
    important: false,
  },
  {
    id: 10,
    title: '독서 마일리지 적립 안내',
    content: '독서 마일리지 제도를 안내드립니다. 독서 마일리지는 독서 활동에 참여할 때마다 적립되며, 적립된 마일리지는 다양한 혜택으로 교환할 수 있습니다.\n\n적립 기준: 서평 작성(100P), 독서토론 참여(150P), 독서프로그램 완료(300P), 독서에세이 제출(200P), 북토크 참석(50P)입니다.\n\n마일리지 사용: 5,000P 이상 적립 시 도서 상품권 교환, 10,000P 이상 적립 시 우수 독서인 가산점 부여, 20,000P 이상 적립 시 해외 도서전 참관 우선 선발 혜택이 있습니다.',
    date: '2025-11-28',
    views: 156,
    author: '독서교육팀',
    attachments: ['독서마일리지_안내서.pdf'],
    important: false,
  },
]

export const reviews: BookReview[] = [
  {
    id: 1,
    type: 'program',
    user: { name: '김서윤', avatar: '/avatars/01.png', department: '국어국문학과' },
    book: { title: '데미안', author: '헤르만 헤세', cover: '/covers/demian.jpg' },
    rating: 5,
    text: '싱클레어의 자아 탐색 여정이 대학생인 지금 읽으니 더욱 깊이 와닿았습니다. "새는 알에서 나오려고 투쟁한다"는 문장이 아직도 마음에 남아있습니다. 독서토론에서 다른 학우들의 해석을 듣고 나니, 같은 책도 이렇게 다르게 읽힐 수 있다는 것이 놀라웠습니다.',
    likes: 72,
    comments: 18,
    timeAgo: '2시간 전',
    category: '문학·예술',
    program: '2025-2학기 독서 마라톤',
  },
  {
    id: 2,
    type: 'program',
    user: { name: '이준혁', avatar: '/avatars/02.png', department: '경영학과' },
    book: { title: '정의란 무엇인가', author: '마이클 샌델', cover: '/covers/justice.jpg' },
    rating: 4,
    text: '공리주의와 자유주의, 공동체주의의 관점에서 정의를 바라보는 다양한 시각을 접할 수 있었습니다. 특히 트롤리 문제에 대한 토론이 흥미로웠고, 경영학을 공부하는 학생으로서 기업 윤리에 대해 다시 생각해 보는 계기가 되었습니다.',
    likes: 58,
    comments: 23,
    timeAgo: '5시간 전',
    category: '인문·사회',
    program: '2025-2학기 북 멘토링',
  },
  {
    id: 3,
    type: 'program',
    user: { name: '박지민', avatar: '/avatars/03.png', department: '생명과학과' },
    book: { title: '이기적 유전자', author: '리처드 도킨스', cover: '/covers/selfish-gene.jpg' },
    rating: 5,
    text: '유전자의 관점에서 생명 현상을 바라보는 도킨스의 통찰이 정말 인상적이었습니다. 이타적 행동도 결국 유전자의 이기적 전략이라는 설명은 생명과학을 전공하는 저에게도 새로운 시각을 제공했습니다. 밈(meme) 개념의 등장도 흥미로웠습니다.',
    likes: 65,
    comments: 15,
    timeAgo: '1일 전',
    category: '자연과학',
    program: '2025-2학기 독서 마라톤',
  },
  {
    id: 4,
    type: 'program',
    user: { name: '최예린', avatar: '/avatars/04.png', department: '철학과' },
    book: { title: '존재와 시간', author: '마르틴 하이데거', cover: '/covers/being-time.jpg' },
    rating: 4,
    text: '난해하기로 유명한 하이데거의 저작이지만, 교수님의 북 멘토링 덕분에 핵심 개념들을 이해할 수 있었습니다. 현존재(Dasein)의 개념과 시간성에 대한 분석은 철학 전공자로서 반드시 거쳐야 할 관문이라 느꼈습니다.',
    likes: 41,
    comments: 12,
    timeAgo: '1일 전',
    category: '인문·사회',
    program: '2025-2학기 북 멘토링',
  },
  {
    id: 5,
    type: 'program',
    user: { name: '정민수', avatar: '/avatars/05.png', department: '컴퓨터공학과' },
    book: { title: '코스모스', author: '칼 세이건', cover: '/covers/cosmos.jpg' },
    rating: 5,
    text: '칼 세이건의 우주에 대한 열정과 경외감이 그대로 전해져 오는 명저입니다. 과학적 사실을 시적인 문체로 풀어낸 것이 인상적이었고, 우주 속 인류의 위치에 대해 깊이 생각하게 되었습니다. 이공계 학생들에게 강력 추천합니다.',
    likes: 53,
    comments: 9,
    timeAgo: '2일 전',
    category: '자연과학',
    program: '2025-2학기 독서 마라톤',
  },
  {
    id: 6,
    type: 'program',
    user: { name: '한소희', avatar: '/avatars/06.png', department: '사학과' },
    book: { title: '삼국유사', author: '일연', cover: '/covers/samguk.jpg' },
    rating: 4,
    text: '한국 고전 중에서도 가장 풍부한 이야기를 담고 있는 삼국유사를 정독할 수 있어 좋았습니다. 단군신화부터 다양한 설화까지, 우리 민족의 정신세계를 엿볼 수 있었습니다. 사학 전공 수업에서 배운 내용과 연결지어 읽으니 더 의미 있었습니다.',
    likes: 38,
    comments: 7,
    timeAgo: '2일 전',
    category: '문학·예술',
    program: '2025-2학기 독서 마라톤',
  },
  {
    id: 7,
    type: 'program',
    user: { name: '윤태호', avatar: '/avatars/07.png', department: '경제학과' },
    book: { title: '국부론', author: '애덤 스미스', cover: '/covers/wealth-nations.jpg' },
    rating: 4,
    text: '경제학의 아버지 애덤 스미스의 대표작을 드디어 완독했습니다. 보이지 않는 손의 원리뿐 아니라 분업, 자본 축적, 자유무역에 대한 그의 체계적인 논증이 인상적이었습니다. 현대 경제학 이론의 뿌리를 확인할 수 있는 소중한 경험이었습니다.',
    likes: 47,
    comments: 14,
    timeAgo: '3일 전',
    category: '인문·사회',
    program: '2025-2학기 북 멘토링',
  },
  {
    id: 8,
    type: 'program',
    user: { name: '강하은', avatar: '/avatars/08.png', department: '영어영문학과' },
    book: { title: '오만과 편견', author: '제인 오스틴', cover: '/covers/pride.jpg' },
    rating: 5,
    text: '원서로 읽으면서 오스틴의 위트와 아이러니를 더 깊이 느낄 수 있었습니다. 엘리자베스와 다아시의 관계가 단순한 로맨스가 아니라 계급, 편견, 자아에 대한 깊은 성찰을 담고 있다는 점을 토론을 통해 재발견했습니다.',
    likes: 61,
    comments: 20,
    timeAgo: '3일 전',
    category: '문학·예술',
    program: '2025-2학기 독서 마라톤',
  },
  {
    id: 9,
    type: 'program',
    user: { name: '서진우', avatar: '/avatars/09.png', department: '물리학과' },
    book: { title: '시간의 역사', author: '스티븐 호킹', cover: '/covers/brief-history.jpg' },
    rating: 4,
    text: '빅뱅부터 블랙홀까지, 우주의 시간에 대한 호킹의 설명은 명료하면서도 깊이가 있었습니다. 물리학 전공자로서 수식 없이 이렇게 명확하게 설명할 수 있다는 것 자체가 놀라웠습니다. 양자역학과 상대성이론의 통합에 대한 그의 비전이 인상적입니다.',
    likes: 34,
    comments: 8,
    timeAgo: '4일 전',
    category: '자연과학',
    program: '2025-2학기 독서 마라톤',
  },
  {
    id: 10,
    type: 'program',
    user: { name: '임채원', avatar: '/avatars/10.png', department: '미술학과' },
    book: { title: '서양미술사', author: 'E.H. 곰브리치', cover: '/covers/art-history.jpg' },
    rating: 5,
    text: '미술사의 바이블이라 불리는 이 책을 독서프로그램을 통해 체계적으로 읽을 수 있어 감사합니다. 곰브리치의 서술은 단순한 양식사를 넘어 각 시대의 예술가들이 왜 그렇게 표현했는지를 이해하게 해줍니다. 미술을 공부하는 모든 학생에게 필독서입니다.',
    likes: 45,
    comments: 11,
    timeAgo: '5일 전',
    category: '문학·예술',
    program: '2025-2학기 북 멘토링',
  },
  {
    id: 11,
    type: 'ogeoseo',
    user: { name: '김도현', avatar: '/avatars/11.png', department: '소프트웨어학과' },
    book: { title: '채식주의자', author: '한강', cover: '/covers/vegetarian.jpg' },
    rating: 5,
    text: '한강 작가의 노벨문학상 수상작을 다시 읽었습니다. 영혜의 거부가 단순한 채식이 아니라 폭력적 세계에 대한 저항이라는 점이 다시 한번 가슴에 와닿았습니다. 세 부분으로 나뉜 서사 구조가 주제를 다층적으로 보여주는 방식이 탁월합니다.',
    likes: 78,
    comments: 25,
    timeAgo: '6시간 전',
    category: '문학·예술',
  },
  {
    id: 12,
    type: 'ogeoseo',
    user: { name: '오수빈', avatar: '/avatars/12.png', department: '정치외교학과' },
    book: { title: '사회계약론', author: '장 자크 루소', cover: '/covers/social-contract.jpg' },
    rating: 4,
    text: '"인간은 자유롭게 태어났으나 어디서나 쇠사슬에 묶여 있다"는 첫 문장부터 강렬합니다. 일반의지(volonté générale)라는 개념이 현대 민주주의에 어떤 영향을 미쳤는지 생각해 보게 되었고, 직접민주주의에 대한 루소의 이상이 오늘날에도 유효한지 고민하게 됩니다.',
    likes: 36,
    comments: 10,
    timeAgo: '1일 전',
    category: '인문·사회',
  },
  {
    id: 13,
    type: 'ogeoseo',
    user: { name: '장민재', avatar: '/avatars/13.png', department: '화학과' },
    book: { title: '종의 기원', author: '찰스 다윈', cover: '/covers/origin-species.jpg' },
    rating: 4,
    text: '자연선택을 통한 진화론의 핵심을 다윈 자신의 문체로 읽는 것은 특별한 경험이었습니다. 갈라파고스 핀치새의 관찰에서 시작된 거대한 이론 체계가 얼마나 치밀한 논증 위에 세워졌는지 감탄하게 됩니다. 과학 고전 중 반드시 읽어야 할 책입니다.',
    likes: 29,
    comments: 6,
    timeAgo: '3일 전',
    category: '자연과학',
  },
  {
    id: 14,
    type: 'ogeoseo',
    user: { name: '배서연', avatar: '/avatars/14.png', department: '교육학과' },
    book: { title: '논어', author: '공자', cover: '/covers/analects.jpg' },
    rating: 5,
    text: '동양 고전의 정수라 할 수 있는 논어를 완독했습니다. 인(仁)과 예(禮)에 대한 공자의 가르침이 2500년이 지난 지금도 울림이 있다는 것이 놀랍습니다. 교육학을 공부하는 학생으로서, "不憤不啓 不悱不發"(분발하지 않으면 깨우쳐 주지 않는다)이라는 교육 철학에 깊이 공감했습니다.',
    likes: 52,
    comments: 16,
    timeAgo: '4일 전',
    category: '문학·예술',
  },
  {
    id: 15,
    type: 'ogeoseo',
    user: { name: '홍지아', avatar: '/avatars/15.png', department: '의예과' },
    book: { title: '엔트로피', author: '제레미 리프킨', cover: '/covers/entropy.jpg' },
    rating: 3,
    text: '열역학 제2법칙을 사회과학적으로 확장한 시도는 흥미로웠으나, 일부 논증에서 과학적 개념을 지나치게 확대 해석한 부분이 아쉬웠습니다. 그럼에도 에너지와 환경 문제를 엔트로피의 관점에서 조망하는 독특한 시각은 충분히 읽을 가치가 있습니다.',
    likes: 18,
    comments: 4,
    timeAgo: '5일 전',
    category: '자연과학',
  },
]

export const classics: Classic100[] = [
  // 문학·예술 (10)
  {
    id: 1,
    title: '논어',
    author: '공자',
    publisher: '을유문화사',
    year: 2020,
    category: '문학·예술',
    description: '동양 철학의 근간이 되는 고전으로, 공자와 그 제자들의 대화를 기록한 책입니다. 인(仁), 의(義), 예(禮), 지(智) 등 유교의 핵심 덕목을 배울 수 있으며, 오늘날에도 인간관계와 자기 수양에 대한 깊은 통찰을 제공합니다.',
    cover: '/covers/classics/analects.jpg',
    isbn: '978-89-324-7380-5',
  },
  {
    id: 2,
    title: '시경',
    author: '작자 미상 (공자 편집)',
    publisher: '민음사',
    year: 2018,
    category: '문학·예술',
    description: '중국 최초의 시가 총집으로, 주나라 초기부터 춘추시대까지의 시 305편을 수록하고 있습니다. 풍(風)·아(雅)·송(頌)으로 분류되며, 당시 민중의 삶과 감정, 사회상을 생생하게 보여주는 동양 문학의 원류입니다.',
    cover: '/covers/classics/shijing.jpg',
    isbn: '978-89-374-3456-7',
  },
  {
    id: 3,
    title: '채식주의자',
    author: '한강',
    publisher: '창비',
    year: 2022,
    category: '문학·예술',
    description: '2016년 맨부커 국제상, 2024년 노벨문학상을 수상한 한강의 대표작입니다. 고기를 거부하는 한 여성의 이야기를 통해 폭력, 욕망, 인간 존재의 근원적 문제를 탐구합니다. 세 편의 연작 소설로 구성된 독특한 서사 구조가 특징입니다.',
    cover: '/covers/classics/vegetarian.jpg',
    isbn: '978-89-364-7234-1',
  },
  {
    id: 4,
    title: '서양미술사',
    author: 'E.H. 곰브리치',
    publisher: '예경',
    year: 2017,
    category: '문학·예술',
    description: '미술사 입문서의 바이블로 불리는 곰브리치의 대표작입니다. 고대 이집트부터 현대 미술까지 서양 미술의 흐름을 일관된 시각으로 서술하며, 왜 예술가들이 특정 방식으로 표현했는지를 이해하도록 돕습니다.',
    cover: '/covers/classics/art-history.jpg',
    isbn: '978-89-7084-456-2',
  },
  {
    id: 5,
    title: '삼국유사',
    author: '일연',
    publisher: '한길사',
    year: 2019,
    category: '문학·예술',
    description: '고려 시대 승려 일연이 편찬한 역사서로, 한국 고대사와 설화, 불교 문화를 담고 있습니다. 단군신화를 비롯한 건국 설화와 다양한 민간 전승이 수록되어 있어, 한국 문화의 원형을 이해하는 데 필수적인 고전입니다.',
    cover: '/covers/classics/samguk-yusa.jpg',
    isbn: '978-89-356-1234-5',
  },
  {
    id: 6,
    title: '오만과 편견',
    author: '제인 오스틴',
    publisher: '펭귄클래식코리아',
    year: 2021,
    category: '문학·예술',
    description: '19세기 영국 사회를 배경으로 엘리자베스 베넷과 피츠윌리엄 다아시의 사랑 이야기를 그린 소설입니다. 위트 있는 대화와 섬세한 인물 묘사를 통해 계급, 결혼, 편견에 대한 날카로운 사회 비평을 담고 있습니다.',
    cover: '/covers/classics/pride-prejudice.jpg',
    isbn: '978-89-01-1234-5',
  },
  {
    id: 7,
    title: '데미안',
    author: '헤르만 헤세',
    publisher: '민음사',
    year: 2020,
    category: '문학·예술',
    description: '소년 싱클레어의 자아 탐색과 성장을 그린 헤세의 대표적 성장소설입니다. 선과 악, 밝음과 어둠 사이에서 진정한 자아를 찾아가는 과정을 그리며, 청년기의 방황과 각성에 대한 보편적 메시지를 전달합니다.',
    cover: '/covers/classics/demian.jpg',
    isbn: '978-89-374-6012-3',
  },
  {
    id: 8,
    title: '햄릿',
    author: '윌리엄 셰익스피어',
    publisher: '열린책들',
    year: 2016,
    category: '문학·예술',
    description: '셰익스피어 4대 비극 중 하나로, 덴마크 왕자 햄릿의 복수극을 다룹니다. "사느냐 죽느냐 그것이 문제로다"라는 유명한 독백에서 드러나듯, 인간 존재의 근본적 질문과 결단의 문제를 깊이 탐구합니다.',
    cover: '/covers/classics/hamlet.jpg',
    isbn: '978-89-329-1567-8',
  },
  {
    id: 9,
    title: '변신',
    author: '프란츠 카프카',
    publisher: '문학동네',
    year: 2019,
    category: '문학·예술',
    description: '어느 날 아침 벌레로 변한 그레고르 잠자의 이야기를 통해 인간 소외와 부조리를 그린 카프카의 대표 중편소설입니다. 현대 사회에서 개인이 겪는 정체성의 위기와 가족 관계의 본질을 날카롭게 포착합니다.',
    cover: '/covers/classics/metamorphosis.jpg',
    isbn: '978-89-546-3456-7',
  },
  {
    id: 10,
    title: '목민심서',
    author: '정약용',
    publisher: '창비',
    year: 2018,
    category: '문학·예술',
    description: '조선 후기 실학자 정약용이 저술한 목민관의 지침서입니다. 관리가 갖추어야 할 덕목과 백성을 위한 정치의 이상을 체계적으로 제시하며, 공직 윤리와 행정의 원칙에 대한 시대를 초월한 가르침을 담고 있습니다.',
    cover: '/covers/classics/mongmin.jpg',
    isbn: '978-89-364-8901-2',
  },
  // 인문·사회 (10)
  {
    id: 11,
    title: '국부론',
    author: '애덤 스미스',
    publisher: '비봉출판사',
    year: 2017,
    category: '인문·사회',
    description: '경제학의 아버지 애덤 스미스의 대표작으로, 자유시장 경제의 이론적 토대를 확립한 고전입니다. 분업, 자본 축적, 자유무역의 원리를 체계적으로 분석하며, "보이지 않는 손"의 개념으로 시장경제의 자기 조절 메커니즘을 설명합니다.',
    cover: '/covers/classics/wealth-nations.jpg',
    isbn: '978-89-376-0456-7',
  },
  {
    id: 12,
    title: '정의론',
    author: '존 롤스',
    publisher: '이학사',
    year: 2019,
    category: '인문·사회',
    description: '20세기 가장 영향력 있는 정치철학서로, "공정으로서의 정의" 개념을 제시합니다. 무지의 베일과 원초적 입장이라는 사고 실험을 통해 사회 정의의 원칙을 도출하며, 자유와 평등의 조화를 모색하는 현대 정치철학의 기념비적 저작입니다.',
    cover: '/covers/classics/theory-justice.jpg',
    isbn: '978-89-561-3456-7',
  },
  {
    id: 13,
    title: '자본론',
    author: '카를 마르크스',
    publisher: '비봉출판사',
    year: 2015,
    category: '인문·사회',
    description: '자본주의 경제 체제를 분석한 마르크스의 대표작입니다. 상품, 화폐, 자본의 개념부터 잉여가치, 자본 축적, 공황에 이르기까지 자본주의의 운동 법칙을 체계적으로 해부하며, 현대 사회과학에 지대한 영향을 미쳤습니다.',
    cover: '/covers/classics/capital.jpg',
    isbn: '978-89-376-0789-1',
  },
  {
    id: 14,
    title: '사회계약론',
    author: '장 자크 루소',
    publisher: '펭귄클래식코리아',
    year: 2018,
    category: '인문·사회',
    description: '프랑스 혁명에 사상적 기초를 제공한 루소의 정치철학서입니다. 인민주권론과 일반의지(volonté générale)의 개념을 통해 정당한 정치 권력의 근거를 탐구하며, 자유와 평등을 실현하는 민주적 공동체의 이상을 제시합니다.',
    cover: '/covers/classics/social-contract.jpg',
    isbn: '978-89-01-2345-6',
  },
  {
    id: 15,
    title: '존재와 시간',
    author: '마르틴 하이데거',
    publisher: '까치',
    year: 2016,
    category: '인문·사회',
    description: '20세기 존재론의 전환점이 된 하이데거의 주저입니다. 현존재(Dasein)의 존재 구조를 분석하며, 세계-내-존재, 불안, 죽음에 대한 깊은 철학적 성찰을 전개합니다. 실존주의와 해석학에 결정적인 영향을 미친 현대 철학의 기념비적 저작입니다.',
    cover: '/covers/classics/being-time.jpg',
    isbn: '978-89-7291-456-7',
  },
  {
    id: 16,
    title: '정의란 무엇인가',
    author: '마이클 샌델',
    publisher: '와이즈베리',
    year: 2023,
    category: '인문·사회',
    description: '하버드대 마이클 샌델 교수의 정치철학 강의를 담은 책으로, 정의에 대한 다양한 철학적 접근을 탐구합니다. 공리주의, 자유주의, 공동체주의 등의 관점에서 현실 사례를 분석하며 독자 스스로 정의에 대해 사유하도록 이끕니다.',
    cover: '/covers/classics/justice.jpg',
    isbn: '978-89-6217-123-4',
  },
  {
    id: 17,
    title: '군주론',
    author: '니콜로 마키아벨리',
    publisher: '까치',
    year: 2020,
    category: '인문·사회',
    description: '르네상스 시대 피렌체의 정치사상가 마키아벨리의 대표작으로, 정치 권력의 획득과 유지에 관한 현실주의적 분석을 담고 있습니다. 도덕과 정치의 관계에 대한 파격적 주장은 근대 정치학의 출발점이 되었습니다.',
    cover: '/covers/classics/prince.jpg',
    isbn: '978-89-7291-789-2',
  },
  {
    id: 18,
    title: '역사란 무엇인가',
    author: 'E.H. 카',
    publisher: '까치',
    year: 2021,
    category: '인문·사회',
    description: '역사학의 본질과 방법론을 탐구한 E.H. 카의 명저입니다. "역사는 현재와 과거의 끊임없는 대화"라는 유명한 정의를 통해 역사적 사실과 해석의 관계, 역사가의 역할에 대한 근본적 성찰을 제시합니다.',
    cover: '/covers/classics/what-is-history.jpg',
    isbn: '978-89-7291-234-5',
  },
  {
    id: 19,
    title: '프로테스탄트 윤리와 자본주의 정신',
    author: '막스 베버',
    publisher: '문예출판사',
    year: 2019,
    category: '인문·사회',
    description: '종교와 경제의 관계를 분석한 사회학의 고전입니다. 프로테스탄티즘의 금욕적 윤리가 근대 자본주의의 발전에 기여했다는 독창적 테제를 제시하며, 문화와 경제 발전의 관계에 대한 새로운 시각을 열어주었습니다.',
    cover: '/covers/classics/protestant-ethic.jpg',
    isbn: '978-89-310-0456-7',
  },
  {
    id: 20,
    title: '유토피아',
    author: '토머스 모어',
    publisher: '서해문집',
    year: 2017,
    category: '인문·사회',
    description: '16세기 영국의 사상가 토머스 모어가 이상적 사회를 상상하여 그린 작품입니다. 사유재산이 없는 평등한 공동체를 묘사하며, 현실 사회의 부조리를 풍자하고 더 나은 사회에 대한 사유를 촉구합니다.',
    cover: '/covers/classics/utopia.jpg',
    isbn: '978-89-7483-456-7',
  },
  // 자연과학 (10)
  {
    id: 21,
    title: '종의 기원',
    author: '찰스 다윈',
    publisher: '사이언스북스',
    year: 2019,
    category: '자연과학',
    description: '자연선택에 의한 진화론을 체계적으로 제시한 생물학의 기념비적 저작입니다. 다윈은 방대한 관찰과 실험 자료를 바탕으로 생물 종의 변이와 적응, 자연선택의 메커니즘을 논증하며 생명과학의 패러다임을 근본적으로 전환시켰습니다.',
    cover: '/covers/classics/origin-species.jpg',
    isbn: '978-89-8371-456-7',
  },
  {
    id: 22,
    title: '코스모스',
    author: '칼 세이건',
    publisher: '사이언스북스',
    year: 2022,
    category: '자연과학',
    description: '천체물리학자 칼 세이건이 우주와 인류의 이야기를 담은 과학 교양서의 걸작입니다. 우주의 탄생부터 외계 생명의 가능성까지 과학적 사실을 시적이고 감동적인 문체로 서술하며, 우주 속 인류의 위치와 의미를 성찰합니다.',
    cover: '/covers/classics/cosmos.jpg',
    isbn: '978-89-8371-789-1',
  },
  {
    id: 23,
    title: '이기적 유전자',
    author: '리처드 도킨스',
    publisher: '을유문화사',
    year: 2023,
    category: '자연과학',
    description: '유전자의 관점에서 생명 현상을 재해석한 혁명적 저작입니다. 이타적 행동을 포함한 모든 생명 현상을 유전자의 자기 복제 전략으로 설명하며, 문화적 유전 단위로서의 밈(meme) 개념을 최초로 제안한 것으로도 유명합니다.',
    cover: '/covers/classics/selfish-gene.jpg',
    isbn: '978-89-324-7456-7',
  },
  {
    id: 24,
    title: '시간의 역사',
    author: '스티븐 호킹',
    publisher: '까치',
    year: 2021,
    category: '자연과학',
    description: '빅뱅부터 블랙홀, 시간의 본질까지 현대 물리학의 핵심 주제를 일반인도 이해할 수 있도록 풀어쓴 과학 교양서입니다. 우주의 기원과 구조, 양자역학과 상대성이론의 통합이라는 물리학의 궁극적 과제를 명쾌하게 소개합니다.',
    cover: '/covers/classics/brief-history-time.jpg',
    isbn: '978-89-7291-567-8',
  },
  {
    id: 25,
    title: '엔트로피',
    author: '제레미 리프킨',
    publisher: '세종서적',
    year: 2020,
    category: '자연과학',
    description: '열역학 제2법칙인 엔트로피 법칙을 사회, 경제, 환경 문제에 적용한 독창적인 저작입니다. 에너지의 불가역적 소산이라는 물리적 원리를 통해 현대 산업문명의 위기를 진단하고 지속 가능한 사회로의 전환을 촉구합니다.',
    cover: '/covers/classics/entropy.jpg',
    isbn: '978-89-8407-456-7',
  },
  {
    id: 26,
    title: '침묵의 봄',
    author: '레이첼 카슨',
    publisher: '에코리브르',
    year: 2018,
    category: '자연과학',
    description: '살충제의 무분별한 사용이 생태계에 미치는 영향을 고발한 환경 고전입니다. DDT 등 화학 살충제가 먹이 사슬을 통해 축적되어 조류와 생태계를 파괴하는 과정을 과학적으로 입증하며, 현대 환경 운동의 출발점이 된 기념비적 저작입니다.',
    cover: '/covers/classics/silent-spring.jpg',
    isbn: '978-89-6263-123-4',
  },
  {
    id: 27,
    title: '부분과 전체',
    author: '베르너 하이젠베르크',
    publisher: '서커스',
    year: 2016,
    category: '자연과학',
    description: '양자역학의 창시자 중 한 명인 하이젠베르크의 자서전적 과학서입니다. 20세기 물리학의 혁명적 발견들이 어떤 대화와 논쟁을 통해 이루어졌는지를 생생하게 기록하며, 과학과 철학, 예술의 관계를 깊이 성찰합니다.',
    cover: '/covers/classics/part-whole.jpg',
    isbn: '978-89-6578-123-4',
  },
  {
    id: 28,
    title: '통섭',
    author: '에드워드 윌슨',
    publisher: '사이언스북스',
    year: 2020,
    category: '자연과학',
    description: '자연과학과 인문학의 통합을 주장한 사회생물학자 에드워드 윌슨의 대표작입니다. 물리학, 화학, 생물학, 사회과학, 인문학의 경계를 넘어 지식의 대통합을 제안하며, 학문 간 융합의 필요성과 가능성을 역설합니다.',
    cover: '/covers/classics/consilience.jpg',
    isbn: '978-89-8371-234-5',
  },
  {
    id: 29,
    title: '숨결이 바람 될 때',
    author: '폴 칼라니티',
    publisher: '흐름출판',
    year: 2023,
    category: '자연과학',
    description: '신경외과 레지던트였던 저자가 폐암 진단을 받은 후 삶과 죽음, 의학의 의미를 성찰한 자전적 에세이입니다. 의사이자 환자로서의 이중적 시선을 통해 인간 존재의 유한성과 그 속에서 의미를 찾는 과정을 감동적으로 그려냅니다.',
    cover: '/covers/classics/when-breath.jpg',
    isbn: '978-89-6596-234-5',
  },
  {
    id: 30,
    title: '파인만의 물리학 강의',
    author: '리처드 파인만',
    publisher: '승산',
    year: 2017,
    category: '자연과학',
    description: '노벨물리학상 수상자 리처드 파인만의 전설적인 물리학 입문 강의를 정리한 책입니다. 역학, 전자기학, 양자역학의 핵심 개념을 파인만 특유의 직관적이고 명쾌한 방식으로 설명하며, 물리학의 아름다움과 재미를 전달합니다.',
    cover: '/covers/classics/feynman-lectures.jpg',
    isbn: '978-89-6139-123-4',
  },
]

export const programs: Program[] = [
  {
    id: 1,
    title: '독서 마라톤',
    description: '한 학기 동안 선정된 도서 5권을 읽고 서평을 작성하는 프로그램입니다. 완주자에게는 독서 마일리지와 인증서가 수여됩니다.',
    date: '2026-03-02 ~ 2026-06-20',
    status: 'upcoming',
    participants: 45,
    maxParticipants: 200,
    category: '자율독서',
  },
  {
    id: 2,
    title: '북 멘토링',
    description: '교수님과 함께 깊이 있는 독서를 경험하는 소그룹 멘토링 프로그램입니다. 멘토 교수님의 지도 아래 고전을 정독하고 토론합니다.',
    date: '2026-03-09 ~ 2026-06-13',
    status: 'upcoming',
    participants: 28,
    maxParticipants: 60,
    category: '멘토링',
  },
  {
    id: 3,
    title: '독서 에세이 대회',
    description: '자유 주제로 독서 에세이를 작성하여 제출하는 공모전입니다. 우수작에는 상장 및 상금이 수여되며, 수상작은 문집으로 발간됩니다.',
    date: '2026-03-02 ~ 2026-04-30',
    status: 'upcoming',
    participants: 0,
    maxParticipants: 500,
    category: '공모전',
  },
  {
    id: 4,
    title: '독서토론 리더 프로그램',
    description: '독서토론 모임을 기획하고 이끌어갈 리더를 양성하는 프로그램입니다. 리더십 교육, 토론 기법 훈련, 실전 토론 운영 경험을 제공합니다.',
    date: '2026-03-16 ~ 2026-06-06',
    status: 'upcoming',
    participants: 12,
    maxParticipants: 30,
    category: '리더십',
  },
  {
    id: 5,
    title: '글로벌 북클럽',
    description: '외국어 원서를 함께 읽고 토론하는 프로그램입니다. 영어, 일본어, 중국어 원서 모임이 운영되며, 원어민 튜터가 토론을 지원합니다.',
    date: '2025-09-01 ~ 2025-12-15',
    status: 'completed',
    participants: 35,
    maxParticipants: 40,
    category: '외국어',
  },
  {
    id: 6,
    title: '저자와의 만남',
    description: '국내 유명 작가를 초청하여 작품 세계와 창작 과정에 대해 이야기 나누는 특별 프로그램입니다. 사전 독서 후 참여하면 더욱 의미 있는 시간이 됩니다.',
    date: '2026-04-15',
    status: 'upcoming',
    participants: 67,
    maxParticipants: 150,
    category: '특별행사',
  },
]
